### PR TITLE
fix: fix switch-cli problem using pnpm

### LINKED ISSUE #92: bug of switching vue version with pnpm
demo: 
[https://github.com/jackson-yyy/vue-demi-bug-demo](url)

## reproduce steps

1. run `pnpm install`
2. check `node_modules/lib/v3/index.cjs`, it is correct.
```javascript
var Vue = require('vue')

Object.keys(Vue).forEach(function(key) {
  exports[key] = Vue[key]
})
```
3. run `pnpm switch:vue2`
4. check `node_modules/lib/v3/index.cjs`, it becomes the source code of v2. it shouldn't be changed.
```javascript
var Vue = require('vue')
var VueCompositionAPI = require('@vue/composition-api')
```

i think it's the problem of pnpm. It use symbol link to link file.

i try to delete files under lib before writing file

```diff
function copy(name, version, vue) {
  vue = vue || 'vue'
  const src = path.join(dir, `v${version}`, name)
  const dest = path.join(dir, name)
  let content = fs.readFileSync(src, 'utf-8')
  content = content.replace(/'vue'/g, `'${vue}'`)
+ fs.unlinkSync(dest)
  fs.writeFileSync(dest, content, 'utf-8')
}
```

it works perfectly now.

### PR DESCRIPTION
**Pull request by jackson-yyy**
fix #92

### CODE REVIEW

**Comment by antfu** [comment]
I kind forgot why I added unlink here, seem like to could just remove it

**Comment by jackson-yyy** [comment]
> I kind forgot why I added unlink here, seem like to could just remove it

thanks for replying~

if use yarn/pnpm, it works perferctly.
but using pnpm, it seems to have a bug.

see #92 , i provided a demo to reproduce this bug.

After adding unlink here, it works normally with pnpm.

File: scripts/utils.js [hunk 1]
```diff
@@ -17,6 +17,9 @@ function copy(name, version, vue) {
   const dest = path.join(dir, name)
   let content = fs.readFileSync(src, 'utf-8')
   content = content.replace(/'vue'/g, `'${vue}'`)
+  try {
```
Comment (antfu) [inline scripts/utils.js:20]:
```suggestion
  // unlink for pnpm, #92
  try {
```
